name: Frontend Vitests with Coverage

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Run vitest with coverage
        run: npx vitest --coverage.enabled true

      - name: Upload coverage report
        if: always() 
        uses:  davelosert/vitest-coverage-report-action@v2
        with:
            name: 'Frontend'
            json-summary-path: coverage/coverage-summary.json
            json-final-path: coverage/coverage-final.json
            working-directory: Frontend


