name: Frontend Vitests with Coverage

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run vitest with coverage
        run: npx vitest --coverage.enabled true

      - name: Upload coverage report
        if: always() 
        uses:  davelosert/vitest-coverage-report-action@v2
        with:
            name: 'Frontend'
            json-summary-path: '.Frontend/coverage/coverage-summary-frontend.json'
            json-final-path: '.Fronted/coverage/coverage-final-frontend.json'

