name: Frontend Vitest Framework

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run vitest
        run: |
          cd Frontend
          npx vitest


